<MyTextInput@TextInput>:
    font_size: '14dp'
    background_color: 0,0,0,0
    cursor_color: 1, 1, 1, 1
    canvas.before:
        Color:
            rgba: 1, 1, 1, 1
    canvas.after:
        Color:
            rgb: 0.059, 0.098, 0.18, 1
        Ellipse:
            angle_start:180
            angle_end:360
            pos:(self.pos[0] - self.size[1]/2.0, self.pos[1])
            size: (self.size[1], self.size[1])
        Ellipse:
            angle_start:360
            angle_end:540
            pos: (self.size[0] + self.pos[0] - self.size[1]/2.0, self.pos[1])
            size: (self.size[1], self.size[1])
        Color:
            rgba: 0.247, 0.573, 0.859, 1
        Line:
            points: self.pos[0] , self.pos[1], self.pos[0] + self.size[0], self.pos[1]
        Line:
            points: self.pos[0], self.pos[1] + self.size[1], self.pos[0] + self.size[0], self.pos[1] + self.size[1]
        Line:
            ellipse: self.pos[0] - self.size[1]/2.0, self.pos[1], self.size[1], self.size[1], 180, 360
        Line:
            ellipse: self.size[0] + self.pos[0] - self.size[1]/2.0, self.pos[1], self.size[1], self.size[1], 360, 540

<RoundedButton@Button>:
    background_color: (0,0,0,0)
    background_normal: ''
    back_color: (1,0,1,1)
    border_radius: [18, 18, 18, 18]
    canvas.before:
        Color:
            rgba: self.back_color
        RoundedRectangle:
            size: self.size
            pos: self.pos
            radius: [18, 18, 18, 18]

MainUI:
<MainUI>:
    orientation: 'vertical'
    TopSection:
        orientation: 'vertical'
        size_hint: 1 , .47
        padding: 20
        spacing: 30
        canvas.before:
            Color:
                rgba: 0.055, 0.718, 1, 1
            Rectangle:
                pos: self.pos
                size: self.size
        Label:
            pos_hint: {'center_x': .5, 'center_y': 0.3}
            size_hint: .8 , 1
            font_size: "40dp"
            text: "Academic Web Scrapper"
        BoxLayout:
            pos_hint: {'center_x': .5, 'center_y': .5}
            size_hint: .8 , None
            height: "40dp"
            BoxLayout:
                size_hint_x: 50
                canvas.before:
                    Color:
                        rgba: 0.059, 0.098, 0.18, 1
                    Rectangle:
                        pos: self.pos
                        size: self.size
                MyTextInput:
                    id: keyword
            BoxLayout:
                size_hint_x: 2
        # TextInput:
        #     pos_hint: {'center_x': .5, 'center_y': .5}
        #     size_hint: .8 , None
        #     height: "40dp"
        #     id: 'keyword'
        #     text: 'Search'
        RoundedButton:
            text: "Search"
            pos_hint: {'center_x': .5, 'center_y': .5}
            size_hint: .25 , None
            height: "40dp"
            back_color: (0.157, 0.455, 0.753, 1.0)
            on_press: app.runScrape(app.root.ids.keyword.text)
    BoxLayout:
        orientation: 'vertical'
        Label:
            text: "Content"
        ScrollView:
            # here we can set bar color
            bar_color: [0, 0, 255, 1]
 
            # here we can set bar width
            bar_width: 12
            BoxLayout:
                orientation: 'vertical'
                Label:
                    text: "Content"
                Label:
                    text: "Content"
                Label:
                    text: "Content"
                Label:
                    text: "Content"
                Label:
                    text: "Content"
                Label:
                    text: "Content"
                Label:
                    text: "Content"
                Label:
                    text: "Content"
                Label:
                    text: "Content"
                Label:
                    text: "Content"
                Label:
                    text: "Content"
                Label:
                    text: "Content"
                Label:
                    text: "Content"
                Label:
                    text: "Content"
                Label:
                    text: "Content"
                Label:
                    text: "Content"
                Label:
                    text: "Content"
                Label:
                    text: "Content"
                Label:
                    text: "Content"
                Label:
                    text: "Content"
                Label:
                    text: "Content"
                Label:
                    text: "Content"
                Label:
                    text: "Content"
                Label:
                    text: "Content"
                Label:
                    text: "Content"
                Label:
                    text: "Content"
                Label:
                    text: "Content"
                Label:
                    text: "Content"
                Label:
                    text: "Content"
                Label:
                    text: "Content"
                Label:
                    text: "Content"
                Label:
                    text: "Content"
                Label:
                    text: "Content"
                Label:
                    text: "Content"
                Label:
                    text: "Content"
                Label:
                    text: "Content"
                Label:
                    text: "Content"
                Label:
                    text: "Content"
                Label:
                    text: "Content"
                Label:
                    text: "Content"
                Label:
                    text: "Content"
                Label:
                    text: "Content"
                Label:
                    text: "Content"
                Label:
                    text: "Content"
                Label:
                    text: "Content"
                Label:
                    text: "Content"
                Label:
                    text: "Content"
                Label:
                    text: "Content"
                Label:
                    text: "Content"
                Label:
                    text: "Content"
                Label:
                    text: "Content"
                Label:
                    text: "Content"
                Label:
                    text: "Content"
                Label:
                    text: "Content"
                Label:
                    text: "Content"
