MainUI:
<MainUI>:
    orientation: 'vertical'
    TopSection:
        orientation: 'vertical'
        size_hint: 1 , .47
        padding: 20
        spacing: 30
        canvas.before:
            Color:
                rgba: 0.055, 0.718, 1, 1
            Rectangle:
                pos: self.pos
                size: self.size
        Label:
            pos_hint: {'center_x': .5, 'center_y': 0.3}
            size_hint: .8 , 1
            font_size: "40dp"
            text: "Academic Web Scrapper"
        TextInput:
            pos_hint: {'center_x': .5, 'center_y': .5}
            size_hint: .8 , None
            height: "40dp"
            id: 'keyword'
            text: 'Search'
        Button:
            text: "Search"
            pos_hint: {'center_x': .5, 'center_y': .5}
            size_hint: .25 , None
            height: "40dp"
            border: 30,30,30,30
    Label:
        text: "Content"
